### ISSUE TITLE
Request parameter(s) clash

### ISSUE THREAD

**Issue by tms320c** [auth0/auth0-PHP#131]
Oauth2Client.php logic depends on request parameter:
`isset($_REQUEST['code'])` 

Thus, if a form uses input name 'code' and the form action should pass Auth0 verification then Oauth2Client gets irrelevant code and fails.

This happens in Laravel 5.3 with most recent Auth0 at least.

**Comment by glena** [comment]
yes, the upcoming version of the sdk will not use REQUEST but the issue here is not that.

can you show me your configuration file (please remove the client_id and secret before posting). The SDK only tries to exchange the user if there is no user logged in (not persisted into the session) so that might be why it is trying to get the code to exchange (https://github.com/auth0/laravel-auth0/blob/02b6300cb8cc71ee99a1c9d12de20f1ca3da1d4c/src/config/config.php#L54-L56).

Also, if you implement your own user repository, you should be able to get from your database the user model instead of getting it from the SDK and avoid asking the sdk for the user profile on each request (not sure if you have a user model in your app or only using the info you get from auth0).

**Comment by fgilio** [comment]
I'm experiencing a related problem: https://github.com/auth0/auth0-PHP/pull/130#issuecomment-269823828

The new change seems to be breaking things in my implementation, which was working ok before.

**Comment by glena** [comment]
@fgilio upgrade to 4.0.10 and try again

**Comment by fgilio** [comment]
Ok, I'll let you know. Thanks!

**Comment by tms320c** [comment]
I have just updated to 4.0.11. Same problem at another line of Auth0 code. If my form contains a field with name 'code':

`ApiException in Oauth2Client.php line 266: invalid_grant: Invalid authorization code

    in Oauth2Client.php line 266
    at Oauth2Client->exchangeCode() in Oauth2Client.php line 399
    at Oauth2Client->getAccessToken() in Auth0Service.php line 65
    at Auth0Service->getUser() in AdminUserRepository.php line 37
`

**Comment by glena** [comment]
The upgrade comment was for fgilio. Did you check my first comment?

You need to change the repo to avoid calling the sdk on each request. Otherwise it will try to get the code and do the exchange if the user is not logged in.

**Comment by tms320c** [comment]
It happens only if a user that is verified by Auth0 is logged in. I use Laravel guard in middleware, so the application tries to auth user at each request

**Comment by glena** [comment]
@tms320c I found the reason of that. Can you upgrade the laravel sdk (auth0/login) to version `4.0.7` and then change the sdk configuration (under `config/laravel-auth0.php`) and make sure this 3 configurations are set to true:

```
    'persist_user' => true,
    'persist_access_token' => true,
    'persist_id_token' => true
```

**Comment by tms320c** [comment]
Great! No problem now! Thank you very much!

**Comment by glena** [comment]
awesome!
