### ISSUE TITLE
Decouple for Guzzle with HTTPlug

### ISSUE THREAD

**Issue by Nyholm** [auth0/auth0-PHP#151]
I just started to use your service but I cannot install this library because I have other dependencies require Guzzle 5. 

I would be happy to help decouple from Guzzle and use the HTTPlug abstraction. 

Disclaimer: Im part of the php-http team. We are creator of HTTPlug and maintainers of Guzzle.

**Comment by glena** [comment]
Hi Nyholm,

I saw HTTPlug some time ago when I was looking to decouple from guzzle but never had  time to implement it. It would be awersome if you can throw a PR.

**Comment by Nyholm** [comment]
Great. I will. Thanks!

**Comment by glena** [comment]
Thank you

**Comment by Nyholm** [comment]
I've started to dig into this issue now. I see that there is no central point of this API. It is basically 4 different API classes that work independent of each other. 

There is also a lot of magic and it would be impossible to to a non-BC breaking update to remove the dependency on Guzzle because of the GuzzleOptions parameters. 

I suggest to start a cleanup (see my PRs) and then move towards something like [GithubAPI](https://github.com/KnpLabs/php-github-api) is doing. See small examples on https://github.com/FriendsOfApi/boilerplate

Any thoughts?

**Comment by glena** [comment]
`I've started to dig into this issue now. I see that there is no central point of this API. It is basically 4 different API classes that work independent of each other.`

Everything is centralized within this class https://github.com/auth0/auth0-PHP/blob/master/src/API/Helpers/ApiClient.php

There is no centralized entry point which is true tho, but it is really 2 different api clients (one for authentication API and one for management API) + an Oauth2 client (Auth0) which uses the Authentication API to work.

`There is also a lot of magic and it would be impossible to to a non-BC breaking update to remove the dependency on Guzzle because of the GuzzleOptions parameters.`

If you inject the HTTPClient you can inject it already configured. If you will rely on the magic of the HTTPPlug library, you can still use this param to configure the HTTP Client (not sure if HTTPPlug can handle the Client configuration or just abstracts the basic API).

I am adding some notes in the PRs.

**Comment by Nyholm** [comment]
> If you inject the HTTPClient you can inject it already configured. 

Yes, I have to inject the HTTPclient configured. 

> If you will rely on the magic of the HTTPPlug library

There is no magic =)

I have to remove the guzzle_options. That will be a BC break. Are you okey with that?

**Comment by glena** [comment]
Good.

Yes, it is not widely used. Later I can figure out if a minor with a big warning is enough or if I should release a mayor.

**Comment by Nyholm** [comment]
Okey, great!

**Comment by cocojoe** [comment]
@glena What were you final thoughts on major vs minor? I would say major as there are breaking changes, see the update PR comments.  However wanted to check this with you first.  Thx

**Comment by glena** [comment]
Yes, it should be a major:
- we are changing the public contract
- Besides it is mostly internal, it is a huge change
