### ISSUE TITLE
Double Login / Logout

### ISSUE THREAD

**Issue by RobMaple** [auth0/auth0-PHP#224]
I've come across a strange issue that seem to allow a user to login twice and then requires logging out twice.

This happens when:
• a user logs in to the secured area of the app
• then navigates back with the browser back button. 
• This prompts the 'Last time you logged in with' login screen which allows you to then login using the remembered account 
• This returns you to the secured area.
• If you then click logout (which uses the logout url endpoint + sdk logout method) you are logged out
• clicking the browser back button at this point still returns you to the secured area as if you are logged in.
• Logging out a second time then means the back button no longer returns you to the secured area and instead prompts the login screen.

After logging out the first time and navigating back I can see that auth0__access_token stored in the session is now different.

**Comment by joshcanhelp** [comment]
@RobMaple - We added state validation in [5.1.0](https://github.com/auth0/auth0-PHP/releases/tag/5.1.0) and when I test with that version, I get a fatal `Invalid state` error, as expected. This might solve your issue, though maybe not in the way you expect. 

To summarize what I'm doing/seeing on my end:

1. Load my local app and clear out all my cookies for that domain
1. Click **Login** which calls `Auth0()->login()`
1. I land on `https://my-domain.auth0.com/login?&response_type=code&state=RANDOM_STRING&etc...` with a prompt to login
1. Enter credentials and submit, get redirected back to my local app here `http://php.localhost.test/?code=AUTH_CODE&state=RANDOM_STRING`
1. Now I'm logged in so I click **Back** and get that "Last time you logged in with..." message
1. Click my credential and get redirected back to my local app here `http://php.localhost.test/?code=DIFFERENT_AUTH_CODE&state=RANDOM_STRING` (note that the state is the same in the second URL because the same one was in the URL)
1. Click **Logout** which calls `Auth0()->logout()`
1. Now I'm logged out so I click **Back** and I get the fatal state error because it's trying to check the same state value that was already validated and deleted

All that to say ... 5.1.0 gets this to work as expected. I'm going to close this but please feel free to report back if you're having the same/similar issue or need help moving to 5.1.0.

**Comment by RobMaple** [comment]
Ok thanks @joshcanhelp 
I'm unable to test right now but the sequence / outcome you described above certainly sounds like it should be fixed. Will report back if theres any related issues though.
