### ISSUE TITLE
Invalid state

### ISSUE THREAD

**Issue by timrabbetts** [auth0/auth0-PHP#252]
Using this within drupal.  

Getting invalid state exception when checking the returned state.  

This function
 `public function validate($state) {
        $valid = $this->store->get(self::STATE_NAME) == $state;
        $this->store->delete(self::STATE_NAME);
        return $valid;
    }`

the store is empty, can you help please?

**Comment by timrabbetts** [comment]
client id, secret and domain are correct I think

**Comment by timrabbetts** [comment]
JWT Leeway 180, JWT Algor = RS256

**Comment by timrabbetts** [comment]
I am using the module.  I have this error with the module, filled out every
thing. I will post my config shortly. Thanks for quick response.

**Comment by timrabbetts** [comment]
this is whats in the settings form 
Client id
h###########################o

Client secret
r#############################################################2

Client Secret is Base64 Encoded (not checked)

Domain
bla.eu.auth0.com

JWT Leeway
180

JWT Signature Algorithm
RS256

**Comment by timrabbetts** [comment]
![autodata](https://user-images.githubusercontent.com/12124608/39173921-fc62fafe-479d-11e8-81f1-4a1a84e9e06d.png)
 seems to match, so the state stuff, it looks like it compares the state after going off to google for oauth and the store is empty thats not correct is it?

**Comment by timrabbetts** [comment]
I think this is some of the drupal module code thats failing, comments say set store to null so store is set to session store, but within getUser it fails with invalid state cause it compares the state to the now empty store.  I am on latest dev version of module, tried stable as well and no bug raise for this on drupal.org.  Thanks for any help, was kinda hoping this just worked.

**Comment by timrabbetts** [comment]
The logs on auth0 say I have logged in successfully so this defo feels like its the module not handling the response correctly.  I'll pester on drupal.org but any help would be great!

**Comment by timrabbetts** [comment]
Maybe if you talk me through the new state process I could try and fix the drupal module?

**Comment by joshcanhelp** [comment]
Let's rewind a bit :) 

First, are you using the module from Github or did you install from Drupal.org? If from Github, how did you install it, composer or git clone or another way? The modules have split a bit and [we're working to sync those back up](https://github.com/auth0/auth0-drupal/pull/89). I'm guessing from here but I want to make sure. If you installed from Github, I'd close the drupal.org thread for now since these are different modules at the moment. 

In short, state is sent to Auth0 in the login link as a URL parameter is you're using SSO:

https://github.com/auth0/auth0-drupal/blob/master/src/Controller/AuthController.php#L198

... or provided to the Lock login widget if you're using the on-page login:

https://github.com/auth0/auth0-drupal/blob/master/src/Controller/AuthController.php#L137

... and stored:

https://github.com/auth0/auth0-drupal/blob/master/src/Controller/AuthController.php#L179

... so we can make sure it comes back intact, which happens in the SDK:

https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L352

Setting `store` in the config to `null` is redundant, sets the storage to be a session store so we can get that value when we return. I'll make a note to just remove that so it doesn't cause confusion. 

You should always have that `state` returned from Auth0 in the callback URL as a parameter so it's unlikely that it's missing. I think you'll need to debug why it's different from what's stored (less likely) or that storage is failing for some reason (more likely). 

Let me know if I can help anymore here or if you find an issue with how we're doing the state checking for your environment.

**Comment by timrabbetts** [comment]
I installed both module and auth0 plugin via composer:

auth0/auth0-php                       5.1.1              Auth0 PHP SDK.
drupal/auth0                          2.x-dev 5d48c87    Single Sign On f...

The store is not set before then we do get a state back and it compares to empty store so I need to know what goes into the store at the start, maybe this is some weird session thing?

Happy to debug module if you can advise.

**Comment by timrabbetts** [comment]
I have installed the auth0-drupal module from github (master branch) and removed the really rubbish drupal.org module.  Now getting a better error message:
Failed to exchange code for tokens: cURL error 6: Could not resolve host: ti####.eu.auth0.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by timrabbetts** [comment]
I think that was a blip as tested it and its working.  Really need to get rid of the module off drupal.org and replace it with this or at least some comments.  Thanks for the help!

**Comment by joshcanhelp** [comment]
@timrabbetts - Thanks for checking back in! We're working on getting the right code up there. I think the main problem there is that it's using endpoints that are deprecated for new accounts. That's all fixed on Github, just need to merge the good architecture that the Drupal module has with the updates on our end.

**Comment by timrabbetts** [comment]
Good stuff, its sort of working right now, so will you merge into master and I can just pull that in future sometime?  Strange cause first time it fails and then it lets me in, let me know when the new code is in and I'll take a look.  If you get a cahnce could you look at my other issues, just want to know if the features exist yet or if they are in scope.  If I wanted to add to this code base would that be okay?

**Comment by joshcanhelp** [comment]
Yes, we'll get those into master soon, it's holding up any improvements we can make. I've got time set aside at the end of this week and next.

**Comment by timrabbetts** [comment]
Thanks
