### ISSUE TITLE
Consider to customize the jwks path

### ISSUE THREAD

**Issue by mabuonomo** [auth0/auth0-PHP#417]
Hi, can you consider to customize the jwks path ('.well-known/jwks.json') in Auth0.php?
```
$jwks        = $jwksFetcher->getKeys($idTokenIss.'.well-known/jwks.json');
```
I'd like to use this library in a our internal project, but our service use a different jwks_uri

Thank you

**Comment by mabuonomo** [comment]
I use the version tag 7.0.0

**Comment by joshcanhelp** [comment]
@mabuonomo - Is your JWKS URL listed in the discovery document for your auth server? You can see the `jwks_uri` key on the URL below for an Auth0 server:

https://auth0.auth0.com/.well-known/openid-configuration

The SDK does not currently do dynamic discovery but it's definitely something we want to add. Would that solve your problem here?
