### ISSUE TITLE
Silent error (getUser() returns null) when no Authorization Code is given

### ISSUE THREAD

**Issue by stumpdk** [auth0/auth0-PHP#444]
### Description

$Auth0->GetUser() returns null, if Authorization Code is not given in URL or POST body.
This results in a silent error, as no exceptions are thrown.

### Reproduction
Instantiate $Auth object
Run $Auth->GetUser();

This will run the exchange() method, which in turn returns false, if no authorization code is given in query or POST body (see https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L513 and https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L700)

### Environment

- **Version of this library used: 7.2**
- **Other relevant versions (language, server software, OS, browser): PHP 7.3**

**Comment by joshcanhelp** [comment]
@stumpdk - Appreciate the report here but this is expected behavior. That method is a bit overloaded but what you're describing is how it was meant to work. You can see the usage here:

https://auth0.com/docs/libraries/auth0-php/basic-use

What would you expect this method to do if there was no user information?

**Comment by jimmyjames** [comment]
Closing this issue given @joshcanhelp's comment above; this is the expected behavior.
