### ISSUE TITLE
Make the CACHE_TTL used in the JWKFetcher configurable.

### ISSUE THREAD

**Issue by ls-yannick-thiel** [auth0/auth0-PHP#450]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, when using a cache in the JWKFetcher, it uses a harcoded TTL:
https://github.com/auth0/auth0-PHP/blob/master/src/Helpers/JWKFetcher.php#L126
https://github.com/auth0/auth0-PHP/blob/master/src/Helpers/JWKFetcher.php#L24

This makes it difficult to make the TTL different if we would like it to. For instance, if we'd like the cache entry to last for 3 days rather than 10 minutes, logic needs to be set in place externally to manually clear the cache at a given rate rather than simply modifying a value in our auth0 configuration. Given many other parameters are available through that configuration (clientID, audiences, supported algorithms, etc...), I would like that this value also be provided through there, so that it can easily be modified as necessary.

A field named "jwks_cache_ttl" would be great, but any configurable field would be sufficient.

### Describe the ideal solution

A config value named "jwks_cache_ttl" which is used as the cache TTL in the JWKFetcher class.

## Alternatives and current work-arounds

Right now, we get by with logic that manually clears the cache based on what is described [here](https://github.com/auth0/auth0-PHP/issues/441) at a configurable rate. We manually update the TTL to something longer on each call. This is far from desirable, as it introduces a lot of logic to get around the immutability of one parameter.

### Additional context

None.

**Comment by ls-gabriel-stone** [comment]
Hi @evansims
After looking at the code changes in the #462 PR, I’m still unsure how the TTL is now configurable. We are using this library for our authentication module and we call the function `decodeJWT` in the `Auth0Service` class. This function will instantiate a new `JWKFetcher` instance which will have the TTL configured to the default 600 seconds. The `getKeys` function from the `JWKFetcher` class is then called which will eventually call the setCacheEntry in the same class which will set the cache with the default TTL: `$this->cache->set($cache_key, $keys, $this->ttl);`  Since there is no way of supplying our own instance of JWKFetcher to the `Auth0Service` class or a way to override the default TTL using the `laravel-auth0` configuration, I’m not sure how the TTL is configurable. Any help is appreciated. Thanks!
