### ISSUE TITLE
The dependency on auth0/php-jwt conflicts with the original lcobucci/jwt

### ISSUE THREAD

**Issue by dunglas** [auth0/auth0-PHP#507]
### Describe the problem

This package depends on `auth0/php-jwt` which is a fork of `lcobucci/jwt`. However, `auth0/php-jwt` uses the same namespaces as `lcobucci/jwt`. This autoloading conflicts between the two libraries when both are installed. It's very common in the Symfony ecosystem because many packages depends on the original version of `auth0/php-jwt` (LexikJwtBundle, the official MercureBundle...).

A possible fix is to rename the root namespace in `auth0/php-jwt`. A better fix would be to use the original version of `lcobucci/jwt` instead of a pinned version of your work. AFAIU, your fork is only required for compatibility with PHP 8, which is now supported by the latest version of `lcobucci/jwt`.

### What was the expected behavior?

No autoloading conflicts between both libraries.

### Reproduction

`composer req auth0/php-jwt lcobucci/jwt`

### Environment

PHP 7, Linux.

**Comment by evansims** [comment]
Hi @dunglas 👋  Thanks for your report. This has been raised [a number of times](https://github.com/auth0/auth0-PHP/issues?q=lcobucci%2Fjwt) previously. As was previously mentioned, this will be resolved in the upcoming 8.0 release. For a number of reasons this will not be changed in the 7.x branch.

**Comment by peterfox** [comment]
@evansims thank you for answering so many issues on this, I can see it getting frustrating as a maintainer. I would suggest that potentially a fix for this is to remove the php-jwt package as a dependency and instead make it a dev dependency for the sake of development and testing. Then make it clear in the installation documentation that it's required to be installed if you're on PHP8 but can use Lcobucci for PHP7, equally that if you're using Lcobucci you must require version 3 or face a load of deprecation warnings. Also then adding a composer suggestion to install it.

The problem with the current approach is most people aren't expecting a namespace conflict when installing and it catching people off guard if they already use Lcobucci or there is a dependency using it that no longer working because the Auth0 package namespace is conflicting.

If you'd like any help with this even I can try to find time to do a PR.
