### ISSUE TITLE
Issues with another bundle

### ISSUE THREAD

**Issue by mlesniak-softkraft** [auth0/auth0-PHP#521]
### Describe the problem

When adding ```lexik/jwt-authentication-bundle``` with auth0 package version 7.9 there are several warnings in composer console like this:

Warning: Ambiguous class resolution, "Lcobucci\JWT\Signer\Hmac\Sha256" was found 2x: in "/var/www/vendor/lcobucci/jwt/src/Signer/Hmac/Sha256.php" and "/var/www/vendor/auth0/php-jwt/src/Signer/Hmac/Sha256.php", the first will be used.

You forked package without changing namespaces and I have problems when working with my app:

Fatal error: Lcobucci\JWT\UnencryptedToken cannot implement Lcobucci\JWT\Token - it is not an interface in /var/www/vendor/lcobucci/jwt/src/UnencryptedToken.php on line 9

Some files loads from auth0 package, some from original one - lcobucci

I'm using PHP 8

**Comment by evansims** [comment]
Hi @mlesniak-softkraft 👋 This issue has come up in other reports. The sub-dependency mentioned is not compatible with ours at this time due to major API changes in their new release (which makes implementation non-trivial) and a lack of back ported PHP 8 support in supported versions (which is why we forked.) The name spacing was necessary for a number of reasons, but is not the core issue you're facing there. Looking at their composer configuration, you will not be able to use `lexik/jwt-authentication-bundle` alongside our library at this time.

A beta of this SDK, v8, is currently available. This will resolve your issues once a final release is made.

**Comment by B-Galati** [comment]
What about adding a conflict entry in `composer.json` then?
