### ISSUE TITLE
Missing instruccions step 2 Configure Auth0 PHP Plugin

### ISSUE THREAD

**Issue by silverxmary** [auth0/auth0-PHP#55]
Following only the tutorial in the step 2 I get the error 
Fatal error: Class 'Auth0\SDK\Auth0' not found

The tutorial should have before the include of the class file.

**Comment by glena** [comment]
hi @silverxmary 

the tutorial focus on using composer as it says in the first step.
It is supposed you already installed the dependency and the autoloader as the [Composer's getting started](https://getcomposer.org/doc/01-basic-usage.md) explains.

Did you complete this step?

**Comment by silverxmary** [comment]
yes but composer doesn't install that dependency... I had to add it manually

**Comment by glena** [comment]
on step 1 https://auth0.com/docs/quickstart/webapp/php/#1-add-needed-dependencies

This command
```composer require auth0/auth0-php:"~1.0"```

installs the dependency

**Comment by silverxmary** [comment]
this is the line I had to add 
require __DIR__ . '/vendor/autoload.php';

**Comment by glena** [comment]
Well this is part of using composer, if you dont know how composer works, there is a link to its quickstart.

I dont think it should explicitly said that you need to require the autoload because it can end up confusing unexperienced developers and make them think they need to require it each time they need to use the SDK. Is better for them to read the quickstart and get familiar on composer (what is and how it works).

Anyway, I really appreciate your feedback.

**Comment by silverxmary** [comment]
ok thanks
