### ISSUE TITLE
Namespace conflict when using the official lcobucci/jwt library

### ISSUE THREAD

**Issue by calcifer1337** [auth0/auth0-PHP#561]
### SDK Version

7.9.1

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

After installing the official lcobucci/jwt library i get errors because the auth0 fork uses the same namespace

### How can we reproduce this issue?

Install the auth0-php library and the lcobucci/jwt library

**Comment by evansims** [comment]
Hi @calcifer1337 👋 Sorry for the inconvenience. The sub-dependency mentioned is incompatible with our library at this time due to major API changes in their new 4.x release (which makes implementation non-trivial) and a lack of back ported PHP 8 support in the 3.x branch we support (which is why we forked.)

A beta of this SDK, v8, is currently available that resolves this issues, and will be released as the new stable in a few weeks time.
