### ISSUE TITLE
ID tokens cannot be decoded because verification fails

### ISSUE THREAD

**Issue by shadowhand** [auth0/auth0-PHP#570]
### SDK Version

8.0.0

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

I have an ID token and when I call `$token = $auth0->decode(token: $jwt)` I get the following error:

```
Authorized Party (azp) claim mismatch in the ID token; expected "care-ops-backend", found "9NwyNHRcD2bNGKz25RwetasltUUchC9A"  
```

This is because of [this validation][1] being misconfigured to use `$tokenAudience` when it should be using `$clientId`. This would be solved by changing `->authorizedParty($tokenAudience)` to `->authorizedParty([$this->configuration->getClientId()])` in the line given (L160).

Additionally, if I remove `audience` from my configuration, I get a different error:

```
Audience (aud) claim mismatch in the token; expected "9NwyNHRcD2bNGKz25RwetasltUUchC9A", found "care-ops-backend, https://roundingwell-care-team.auth0.com/userinfo"
```

This is because the [default audience][2] is misconfigured. As far as I can tell, the only possible default audience is for ID tokens only, and that default would be:

```php
if (count($tokenAudience) === 0 && $this->type === self::TYPE_ID_TOKEN) {
    $tokenAudience[] = $this->configuration->formatDomain() . '/userinfo';
}
```

[1]: https://github.com/auth0/auth0-PHP/blob/8.0.0/src/Token.php#L160
[2]: https://github.com/auth0/auth0-PHP/blob/8.0.0/src/Token.php#L143-L146

### How can we reproduce this issue?

Attempt to call `$auth0->decode($jwt)` with any `$jwt` that is an ID token.

### Additional context

It also appears that [the documentation for ID token validation][1] is incorrect, because it states:

> The audience value for the token must match the client ID of the application as defined in your Application's Settings in the Client ID field.

The reality is that the `azp`, **NOT** `aud`, will be set to the application's Client ID value.

[1]: https://auth0.com/docs/security/tokens/id-tokens/validate-id-tokens

**Comment by evansims** [comment]
Thanks, @shadowhand 👋 Appreciate you raising the issue! Running a bit short on time today, but I will investigate this one tomorrow and get back with you!

**Comment by shadowhand** [comment]
@evansims any update on this?

**Comment by evansims** [comment]
Hey @shadowhand 👋 Thanks again for raising this, I do appreciate it.

So, testing out this change, but it actually breaks the expected behavior of the SDK when decoding an ID Token returned from Auth0 after authentication in my tests using, for example, our PHP quickstart. I'm trying to figure out why this is broken for you in your particular case; can you share what your class instantiation/configuration looks like? I might be overlooking something in my testing.

**Comment by shadowhand** [comment]
By comparison, here is a decoded token that I generated from a dev Machine to Machine application:

```json
{
  "iss": "https://roundingwell-care-team.auth0.com/",
  "sub": "49rRUxuM3CQKjYe1njeMfr4iGUXXEHit@clients",
  "aud": "care-ops-backend",
  "iat": 1632400985,
  "exp": 1632487385,
  "azp": "49rRUxuM3CQKjYe1njeMfr4iGUXXEHit",
  "scope": "read:action_forms create:action_form_responses",
  "gty": "client-credentials"
}
```

Once again, the `azp` is the Client ID of the application.

**Comment by shadowhand** [comment]
In neither of these cases is the `aud` set to the Client ID of the application. In all my time using Auth0, I have **NEVER** seen the Client ID be included in the `aud` of a token, so I don't understand why this would be a default. Nor have I ever seen the audience of a client be set in `azp`.

Previously, before upgrading to 8.0.0, my token verification was pretty basic: `iss` and `aud`.  Those verifications work just fine, **except** when audience is not defined and the incorrect Client ID injection happens. The problematic part is the usage of `$tokenAudience` for `azp` verification, which cannot be disabled and is always wrong for ID tokens.

In fact, I found [this Auth0 community post][1] that confirms what I am saying: `azp` is always set to Client ID.

[1]: https://community.auth0.com/t/azp-field-in-the-access-token/46724/3

**Comment by shadowhand** [comment]
Here's another possibly useful data point, found in this [StackOverflow answer][1]:

> ## OIDC ID Tokens
> OIDC has ID Tokens in addition to Access tokens. The OIDC spec is explicit on the use of the aud claim in ID Tokens. (openid-connect-core-1.0)
>
>> `aud`
>> REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
>
>furthermore OIDC specifies the azp claim that is used in conjunction with aud when aud has more than one value.
>
>> `azp`
>> OPTIONAL. Authorized party - the party to which the ID Token was issued. If present, it MUST contain the OAuth 2.0 Client ID of this party. This Claim is only needed when the ID Token has a single audience value and that audience is different than the authorized party. It MAY be included even when the authorized party is the same as the sole audience. The azp value is a case sensitive string containing a StringOrURI value.

[1]: https://stackoverflow.com/a/60937260

**Comment by evansims** [comment]
👋 Thanks for the extra background, @shadowhand! Really appreciate your thoughtful and detailed responses as we try to figure this one out. I think I see where the confusion is stemming from: what we're really talking about here are Access Tokens, rather than ID Tokens. That's why these changes break our quickstart: it will break validation for ID Tokens, but not Access Tokens.

As an example, here is an access token as Auth0 might return it today:
```js
{
  "iss": "https://evansims.us.auth0.com/",
  "sub": "auth0|5f7f0bd6259a3f007183eb08",
  "aud": [
    "example:RS256",
    "https://evansims.us.auth0.com/userinfo"
  ],
  "iat": 1632417411,
  "exp": 1632503811,
  "azp": "q2W946Xx8CL1VPZszal4JC2zNH3u2bSr",
  "scope": "openid profile email"
}
```

And here is an ID token as Auth0 returns it today:
```js
{
  "nickname": "hello",
  "name": "hello@evansims.com",
  "picture": "https://s.gravatar.com/avatar/b5c881f86925d50c0f4232c1c6e5d93e?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fhe.png",
  "updated_at": "2021-09-23T17:45:50.338Z",
  "email": "hello@evansims.com",
  "email_verified": true,
  "iss": "https://evansims.us.auth0.com/",
  "sub": "auth0|5f7f0bd6259a3f007183eb08",
  "aud": "q2W946Xx8CL1VPZszal4JC2zNH3u2bSr",
  "iat": 1632420571,
  "exp": 1632456571,
  "nonce": "..."
}
```

The formats are similar, but there are nuanced differences. For ID Tokens, `aud` is, in fact, the Client ID; it is only for Access Tokens where that differs. That's where the confusion lies between us on this one, and why the PR breaks token claim checks as used in the quickstarts.

You probably noticed that `decode()` processes all tokens passed to it as ID Tokens at present. The `Auth0\SDK\Token` class does have a flag for overriding this default to use `Auth0\SDK\Token::TYPE_TOKEN` instead, but it's not, at present, exposed through the `decode()` method (note to self: do that.) In any event, Access Tokens will validate as ID tokens in many cases, but there are differences as you're seeing here. Importantly to this discussion, we only currently check the `azp` claim against ID Tokens, but this claim is not always present in all cases.

When validating Access Tokens, where an `aud` claim will contain custom API identifiers and other information, you'll want to supply any custom identifier and the client ID during SDK configuration using the `audience` array, or you can do it during runtime such as our quickstart application does: https://github.com/auth0-samples/auth0-php-api-samples/blob/main/src/Application.php#L86-L88

**Comment by shadowhand** [comment]
🤦‍♂️ okay, let me just confirm what I am hearing...

The problem I am experiencing is that the default for `decode($token)` is to expect an ID Token and our application is requesting Access Tokens, not ID Tokens. And as of right now, there is no way to use `Auth0::decode()` on a token other than ID tokens.

**Comment by evansims** [comment]
You can use `decode()` to validate an access token, you simply need to configure your `audience` during initialization in the way I mentioned/as the quickstart demonstrates.

**Comment by shadowhand** [comment]
I am, and have always been, configuring my `audience`:

![image](https://user-images.githubusercontent.com/38203/134569196-cb17d22b-6868-447d-a1e8-04212f452b4c.png)

**Comment by shadowhand** [comment]
> Our of curiosity, is your application doing authentication using a client-side library like our SPA.JS SDK, and that's passing the token back to a PHP backend? 

Exactly right. Users login via SPA.JS and then the token is sent to our backend API as `Authorization: Bearer {token}` at which point we decode it and use it.

**Comment by shadowhand** [comment]
Validating an access token using `$auth0->decode($token)` does not work because:

>   Authorized Party (azp) claim mismatch in the ID token; expected "care-ops-backend", found "9NwyNHRcD2bNGKz25RwetasltUUchC9A"  

Which is due to [this line][1] of `Token.php` which is entirely different for access tokens and will never work as expected. Setting `audience` in configuration will not fix this, but this does:

```php
$token = $auth0->decode($token, tokenAudience: [ $container->get('auth0.identifier'), $container->get('auth0.client') ]);
```

A rather odd work around, but it will let me proceed with the upgrade. Looking forward to being able to do:

```php
$token = $auth0->decode($token, tokenType: Token::TYPE_TOKEN);
```

[1]: https://github.com/auth0/auth0-PHP/blob/8.0.0/src/Token.php#L156-L160

**Comment by evansims** [comment]
Yay, happy that's working, at least! And yup! Configuring it that way is the right solution for now, which is the same approach the QS takes, just by setting the global `audience` rather than expressly defining it on the method. Either way, supplying the array with those contents will allow it to pass validation. 

I've added a backlog item to introduce support on `decode()` for expressly flagging a token as an Access Token for cases like this, as I do agree that would be more helpful than needing to write your own interface for the Token class or working with the audiences this way.
