### ISSUE TITLE
Helper method to retrieve the available scopes as array for a decoded access token

### ISSUE THREAD

**Issue by AndreasA** [auth0/auth0-PHP#612]
### What should be added?

It would be nice if their were a helper method to get the available scopes of an access token (object). maybe also a hasScope.

I know something like this is available on the  auth0 session but that doesn't help if the access token is decoded manually.

**Comment by evansims** [comment]
Hey @AndreasA 👋 In the case of a stateful request, the `Auth0\SDK\Auth0::getCredentials()` method returns a 'accessTokenScope' property, which is an array containing all of the token scopes. We don't currently have a built-in means of doing this for stateless requests, but that's something that could be added easily enough. A new method on the `\Auth0\SDK\Token` class would probably make the most sense.

**Comment by AndreasA** [comment]
@evansims as mentioned it is not that important, it would just be a nice helper function. It is quite easy to get the correct scopes using `toArray` and explode anyway.
However, it would still be useful 😄

**Comment by evansims** [comment]
After some reflection and experimenting with this, I've decided not to include this in the Token class. Since the Token class has the dual duty of offering a common interface for both Access Tokens (which contain scopes) and ID Tokens (which do not) I'm decided it really isn't the best place for it. I'm going to backlog this feature request for a bit while I think about a more elegant way to approach this, but as you mentioned, it's simple enough for the host application to determine how best to fetch that information for itself for the time being.
