### ISSUE TITLE
Error thrown when attempting to verify access token

### ISSUE THREAD

**Issue by phy9pas** [auth0/auth0-PHP#712]
### Checklist

- [X] The issue can be reproduced in a a sample app (either [webapp](https://github.com/auth0-samples/auth0-php-web-app) or [api](https://github.com/auth0-samples/auth0-php-api-samples)) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-PHP#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-PHP/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-PHP/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-php) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.5

### PHP Version

PHP 8.1

### Description

After updating to the latest version I get the following error thrown when verifying and validating an access token:
`Could not find a PSR-17 compatible request factory. Please install one, or provide one using the `setHttpRequestFactory()` method`

The changelog for the most recent version said that I should raise an issue if I see problems following the latest updates I should raise an issue here.

### How can we reproduce this issue?

I'm using the following code to verify the access token:

`$token = new \Auth0\SDK\Token($auth0_config, $token, \Auth0\SDK\Token::TYPE_TOKEN);
$token->verify();
$token->validate();`

**Comment by evansims** [comment]
Hi @phy9pas 👋 Thanks! What PSR-17 implementation/library is your project using?

**Comment by phy9pas** [comment]
Hello, thanks the the response

I'm not specifying a PSR-17 implementation, as far as I know.

When I set up the auth0 library I use this format:

`$auth0_config = new \Auth0\SDK\Configuration\SdkConfiguration([
            'domain' => ....,
            'clientId' => ....,
            'cookieSecret' => ...,
            'tokenJwksUri' => ....,
            'audience' => [ ....]
        ]);
        $token = new \Auth0\SDK\Token($auth0_config, $token, \Auth0\SDK\Token::TYPE_TOKEN);

        $token->verify();

        $token->validate();
`

I've tried specifying a different httpRequestFactory like this

`
$requestFactory = new \Nyholm\Psr7\Factory\Psr17Factory();
$auth0_config->setHttpRequestFactory($requestFactory);
`

But that didn't make any difference.

Are you able to give me any more info about how I'd find out what PSR-17 implementation I'm using?

Thanks

**Comment by evansims** [comment]
Hi @phy9pas 👋 The SDK [requires](https://github.com/auth0/auth0-PHP#requirements) PSR-18, PSR-17 and PSR-7 implementations to be installed in your project, so you definitely have something floating around that appears to fulfill those interfaces.

The SDKs makes a best effort attempt to auto-discover implementations available in a project using the Composer APIs, so usually it “just works” without needing any specific configuration. Sounds like if it was working for you before 8.5, our new auto-discovery has probably just lost the detection rules for whatever your project is using.

Can you run `composer show --direct` from your project directory and share the output? That might tell us.

**Comment by phy9pas** [comment]
Hi Evan, thanks for this.
Is it okay if I email these details to you rather than posting them here as I'd rather not expose all my project dependancies publicly?

**Comment by evansims** [comment]
Hi @phy9pas, sure, no problem. You can send it to evan.sims@okta.com and I'll have a look.

**Comment by evansims** [comment]
Hey @phy9pas 👋 Did you happen to send that email yet? Just want to make sure it wasn't caught in spam limbo on my end.

**Comment by phy9pas** [comment]
Hello, I actually sent a message last week to ***@***.*** but you
mustn't have got it. I've copied it below, thanks

Regarding the auth0 issue you've been helping me with - here is the export
of project dependencies you asked for. I hope you don't mind me emailing
them to you rather than pasting them in to the ticket, I just wanted to
avoid exposing more information publicly than was absolutely necessary. I'm
happy to continue the rest of the discussion on the ticket though.

advanced-custom-fields/advanced-custom-fields-pro        6.0.7
auth0/auth0-php                                          8.5.0
     PHP SDK for Auth0 Authentication and M...
aws/aws-sdk-php                                          3.262.3
     AWS SDK for PHP - Use Amazon Web Servi...
composer/installers                                      v2.2.0
     A multi-framework Composer library ins...
freemius/bp-toolkit-pro                                  3.6.0
humanmade/s3-uploads                                     3.0.6
     WordPress plugin to store uploads on S3
koodimonni-language/en_gb                                6.1.1
     Full WordPress translation (including ...
oscarotero/env                                           v2.1.0
     Simple library to consume environment ...
phpunit/phpunit                                          10.0.19
     The PHP Unit Testing framework.
roave/security-advisories                                dev-master
08c832d Prevents installation of composer pack...
roots/wordpress                                          6.1.1
     WordPress is open source software you ...
roots/wp-config                                          1.0.0
     Collect configuration values and safel...
roots/wp-password-bcrypt                                 1.1.0
     WordPress plugin which replaces wp_has...
squizlabs/php_codesniffer                                3.7.2
     PHP_CodeSniffer tokenizes PHP, JavaScr...
stripe/stripe-php                                        v10.11.0
     Stripe PHP Library
vlucas/phpdotenv                                         v5.5.0
     Loads environment variables from `.env...
wpackagist-plugin/advanced-cron-manager                  2.5.0
wpackagist-plugin/auth0                                  4.5.0
wpackagist-plugin/bbpress                                2.6.9
wpackagist-plugin/buddypress                             11.1.0
wpackagist-plugin/elementor                              3.12.0
wpackagist-plugin/gd-bbpress-attachments                 4.5
wpackagist-plugin/post-type-switcher                     3.2.1
wpackagist-plugin/remove-dashboard-access-for-non-admins 1.1.5


Thanks

Peter

**Comment by evansims** [comment]
Hey @phy9pas 👋 Thanks, and sorry, not sure why that wouldn't have come through!

It appears your app is getting `guzzlehttp/guzzle` and `guzzlehttp/psr7` as transient dependencies of `awks-sdk-php`, https://packagist.org/packages/awks/awks-sdk-php.

`guzzlehttp/psr7` fulfils the `http-factory-implementation` (PSR-17) requirement, so I'm not certain why it wouldn't be discovering it, unless perhaps a version below 2.0 is getting imported for some reason.

Can you try using `composer require guzzlehttp/guzzle:^7.4.5 guzzlehttp/psr7:^2.3`, and see if that resolves the issue? Those dependencies are already present in your app, but this promotes them to direct dependencies instead of transients.

**Comment by evansims** [comment]
Hey @phy9pas 👋 Thanks for the update.

OK, that's extremely bizarre. Upgrading those Guzzle packages shouldn't have resulted in all those `psr-discovery` packages from only then just getting installed – those have no interdependencies at all, so they should have been installed beforehand. The fact they weren't there explains why auto-discovery wasn't working — your application wasn't importing them at all.

Likewise, passing a factory explicitly as you did should definitely be working.

Can you try deleting your application's `./vendor` subdirectory and `./composer.lock` file, and then running `composer install` and checking if the resulting clean dependency install changes anything?

If you continue to have issues, try temporarily removing `roave/security-advisories` and repeating that process. That package is imposing some strict version restrictions that could potentially be causing dependency installation issues.

**Comment by danmenzies** [comment]
Hi, @evansims. I'm working on the same code base as @phy9pas.

First up, thanks for your help and suggestions so far. Our team have been **really** impressed with how responsive you are. It's really appreciated.

So... after the last round of feedback, we ended up:

1. Deleting the `vendor` directory
2. Deleting the `composer.lock` file
3. Removing `roave/security-advisories`
4. Running `composer install`

We also ended up doing some more logging, and according to that, our `$auth0_config` is using `\GuzzleHttp\Psr7\HttpFactory()` by default, now.

Sadly, we're still receiving the same error message.

For a little more context, here's the full block of code that's triggering the issue (redacted in parts, of course)

```php
$jwks_uri = 'https://' . ▒▒▒▒▒▒▒▒ . '/.well-known/jwks.json';
$auth0_config = new \Auth0\SDK\Configuration\SdkConfiguration([
    'domain' => ▒▒▒▒▒▒▒▒,
    'clientId' => ▒▒▒▒▒▒▒▒,
    'cookieSecret' => ▒▒▒▒▒▒▒▒,
    'tokenJwksUri' => $jwks_uri,
    'audience' => [ $audience ]
]);
$token = new \Auth0\SDK\Token($auth0_config, $token, \Auth0\SDK\Token::TYPE_TOKEN);
```

...we've also tried "manually overriding" the Guzzle factory used; but that had no effect (likely because it was already using that one anyway:

```php
$jwks_uri = 'https://' . ▒▒▒▒▒▒▒▒ . '/.well-known/jwks.json';
$auth0_config = new \Auth0\SDK\Configuration\SdkConfiguration([
    'domain' => ▒▒▒▒▒▒▒▒,
    'clientId' => ▒▒▒▒▒▒▒▒,
    'cookieSecret' => ▒▒▒▒▒▒▒▒,
    'tokenJwksUri' => $jwks_uri,
    'audience' => [ $audience ]
]);
$auth0_config->setHttpRequestFactory(new \GuzzleHttp\Psr7\HttpFactory());
$token = new \Auth0\SDK\Token($auth0_config, $token, \Auth0\SDK\Token::TYPE_TOKEN);
```

We're still stumped, here. Any additional insight, or any ideas you could offer would be **greatly** appreciated.

Thanks in advance!

**Comment by evansims** [comment]
Hey @danmenzies 👋 Thanks!

Looks like you're assigning`httpRequestFactory` *after* the `SdkConfiguration` constructor is being fired, at instantiation time.

It's throwing that error in both examples because the interface validation phase occurs during instantiation; if a factory is not assigned at instantiation time, it falls back to performing an autodiscovery attempt, which is broken for you. (Still quite perplexed as to why that process isn't working in your case. 😕)

With discovery unfortunately not working, you'll need to create your PSR interfaces beforehand, and pass them to the new SdkConfiguration during instantiation. Try something like this:

```php
<?php

use Auth0\SDK\Configuration\SdkConfiguration;
use Auth0\SDK\Token;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Psr7\HttpFactory as GuzzleFactory;

$httpFactory = new GuzzleFactory();
$httpClient = new GuzzleClient();

$configuration = new SdkConfiguration(
    domain: '...',
    clientId: ...,
    cookieSecret: '...',
    audience: [ $audience ],

    // The following shouldn't be necessary if auto-discovery was working, but if
    // it's failing for one of these, it's probably not going to work for any of
    // them:
    httpRequestFactory: $httpFactory,
    httpResponseFactory: $httpFactory,
    httpStreamFactory: $httpFactory,
    httpClient: $httpClient
);

$token = new Token(
    configuration: $configuration,
    jwt: '...',
    type: Token::TYPE_ACCESS_TOKEN
);
```

It looks like your application might be stateless, and only just working with access tokens? If that's the case, you can streamline things a bit by setting up the SdkConfiguration like this:

```php
$configuration = new SdkConfiguration(
    strategy: SdkConfiguration::STRATEGY_API,
    // cookieSecret: '...', <-- This is not needed in statelessly configured apps.

    // Other properties...
);
```

This ensures the SDK doesn't try to engage any stateful mechanisms, like session cookies.

Also, you really shouldn't need to define the `tokenJwksUri` manually, unless your use case is for working with non-Auth0-issued tokens. The SDK discovers the JWKS automatically for you, based on the configured `domain`, for Auth0 purposes. But if that isn't the case, you're fine with how you're doing it. 👍

**Comment by danmenzies** [comment]
This is amazing, @evansims. Thanks, I'll give it a whirl when I'm back in front of the tools, Monday morning. 

Thank you :D

**Comment by evansims** [comment]
Sorry to hear that didn't work either, @danmenzies. ☹️ I'm honestly at a loss to explain why this is occurring for you. I'll keep thinking about it as well, although for the moment I'm out of troubleshooting suggestions. Please do let me know if you figure anything out in the meantime.

**Comment by evansims** [comment]
Going to close this thread since we're in a holding pattern at the moment, but do feel free to circle back and we can continue the conversation if anything changes
