### ISSUE TITLE
Adding an explanation to the StateException regarding the possible reasons for the access token being missing.

### ISSUE THREAD

**Issue by luckpoint** [auth0/auth0-PHP#718]
### Checklist

- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am seeking an explanation for why the access token might be missing. 
The StateException does not provide detailed information.

Here is an excerpt from Auth0#renew:

```php
$response = $this->authentication()->refreshToken($refreshToken, $params);
$response = HttpResponse::decodeContent($response);
if (! isset($response['access_token']) || '' === trim($response['access_token'])) {
  $this->clear();
  throw \Auth0\SDK\Exception\StateException::failedRenewTokenMissingAccessToken();
}
```

The causes of errors:
* Rate limit error (429)
* Denial of access through api.access.deny() in Actions (500)
* Other reasons

A possible solution would be to modify the methods in StateException to accept and set a status code. 
This way, the application could catch a StateException and retrieve its statusCode.
Or create a separate method and message for each cause.

**Comment by evansims** [comment]
Hi @luckpoint 👋 My apologies, but I think I'm a bit confused about the context of your question. Is this an actual issue being encountered, or a theoretical condition you're trying to catch?

Those conditions should never occur. Network request failures like you've described (429s, 500s, etc.) are captured by the host application's HTTP client library. Those libraries will throw `Psr\Http\Client\ClientExceptionInterface` exceptions in those conditions.

The SDK catches those `ClientExceptionInterface` exceptions. It wraps the exceptions and [throws an `Auth0\SDK\Exception\NetworkException` for the host application to intercept](https://github.com/auth0/auth0-PHP/blob/13228c699c6e77f52aa5417c2a21edb49709c5ca/src/Utility/HttpRequest.php#L273). These `NetworkException` objects do encapsulate the original `ClientExceptionInterface` and can be evaluated by the host application to determine the cause of the network failure, using [`Exception::getPrevious()`](https://www.php.net/manual/en/exception.getprevious.php).

As such, failures to retrieve access tokens during token refreshes due to network conditions will never raise a StateException. It will instead raise a NetworkException, which does include the reason for the exception, as provided by the underlying HTTP library.

Beyond that, the SDK is purely working with what the API responds to us with. Methods issue their API calls, and return the API responses as PSR-7 messages (ResponseInterface objects.) We don't have any additional insight beyond that response that could be returned, and is already available from the Tenant logs.

**Comment by luckpoint** [comment]
@evansims Thanks for your detailed answer. I understand.
