### ISSUE TITLE
HTML Entity Encoding of received cookies can lead to invalid state errors 

### ISSUE THREAD

**Issue by lochiiconnectivity** [auth0/auth0-PHP#764]
### Checklist

- [X] This can be reproduced in [the quickstart sample application](https://github.com/auth0-samples/auth0-php-web-app).
- [X] I have reviewed [the README.md](https://github.com/auth0/auth0-PHP/blob/main/README.md) and have not found a solution.
- [X] I have reviewed [the EXAMPLES.md](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/auth0-PHP/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/auth0-php) and have not found a solution.
- [X] I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [X] I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### SDK Version

8.7

### PHP Version

PHP 8.2

### Description

HTML Entity Encoding of received cookies can lead to invalid state errors - some security frameworks will perform HTML Entity Encoding of the cookie data prior to being seen by the CookieStore, this can lead to failure to recover the values such as the state and 'invalid state' errors at token exchange time.

### How can we reproduce this issue?

Deploy this SDK on a system which includes HTML Entity Encoding of received cookies, such as under various security frameworks.

**Comment by shadowhand** [comment]
Let's not be cryptic, what frameworks or packages do this?

**Comment by lochiiconnectivity** [comment]
No intention to be cryptic here this was observed in the wild in a third party platform which was HTML encoding all input including cookies, (the author of which has stated that this is a security framework, I do not know which but clearly it was configured to do this) ,  it was not obvious what led to the inability to retrieve the state from the cookie store - when debugging we saw that none of the keys of the cookie were valid JSON as they contained `&quot;` as opposed to `"`

**Comment by shadowhand** [comment]
@lochiiconnectivity again, please name the package or platform. This is NOT a standard security practice and is extremely misguided. No one should be blindly applying `htmlspecialchars` on input, because the correct thing to do is _only use htmlspecialchars() out **output**_.

**Comment by lochiiconnectivity** [comment]
_Discovering this would cause me to immediately drop said package or platform_

I’m glad you feel so idealistic about this, however we observed this in the wild and it led to failure of your SDK to operate, it’s something we have no control over and naming and shaming the platform won’t help.

It doesn’t seem to be a huge concession on your part to acknowledge that this happens and accept the patch.

However given how many unhelpful “invalid state” answers exist out on community forums which don’t give users any ability to help themselves with it , I would have hoped you would have been more accommodating of this.

If you don’t believe that this patch adds value to the SDK or is safe/appropriate , and can’t add any further constructive comments on it , then feel free to close the M/R - I will instead raise an enterprise support ticket and ask the product team to review this.

**Comment by shadowhand** [comment]
> You could also argue that we don’t expect URLEncoding [sic]

That would be incorrect, as URL encoding of data transmitted by a URL (such as state, etc) _should_ be encoded per HTTP specifications. When people have trouble with state, in my experience it is often because they are double encoding and corrupting the state.

> however we observed this in the wild and it led to failure of the SDK to operate

That is correct, because the SDK should _not_ be trying to account for backwards security practices.

**Comment by lochiiconnectivity** [comment]
your opinions noted.

**Comment by evansims** [comment]
👋 Thanks for raising this @lochiiconnectivity, and for sharing your insight on this as well @shadowhand.

I sympathize with your situation on this @lochiiconnectivity, but this would simply be too destructive and potentially dangerous a change to apply broadly to the SDK. As @shadowhand noted, this opens up the potential for security concerns. At a minimum, it would be a significant and most likely breaking change that would invalidate sessions for users of all applications that implement the SDK.

I'm afraid this isn't a road we can take for the SDK. However, you could create your own storage class based on CookieStore that implements this, and simply have it live inside your app. Just configure the SDK at initialization time to use your storage class instead of the internal one.

I'll close this for now as it is not actionable for us, but feel free to keep the discussion going, if you have further questions.

**Comment by evansims** [comment]
I certainly understand where you're coming from. However, I feel this is really more appropriate for inclusion in the application layer, rather than the SDK. I can assure you the storage API we expose is stable, well-supported, and intended for precisely these sorts of cases.

**Comment by lochiiconnectivity** [comment]
At the application layer we only have two choices

One is to ingest , decode and manipulate the cookie data and then write that back to the shared environment , we have to do this each time before each method call. 

The other is, as you said, fork the storage backend, and maintain this fork (including backporting any security fixes to it).

Neither is a great situation, we are talking about logic buried within the storage layer that isn’t easily accessible to the end user.

**Comment by shadowhand** [comment]
> One is to ingest , decode and manipulate the cookie data and then write that back to the shared environment

Because of the broken nature of the provider/package (which I _really_ think needs to be named for the benefit of the community) this is probably the solution you will need to take. The first step to a solution will be accepting that said provider/package is _doing things wrong_.
